### ISSUE TITLE
Don't use this api anymore

### ISSUE THREAD

**Issue by drewnichols** [dirk/sales_tax#1]
Apparently Avalara is no longer offering this free api. I've been getting incorrect rates since 1/1/2017 in some areas. 

https://community.avalara.com/avalara/topics/california-state-tax-discrepancy

**Comment by dirk** [comment]
@drewnichols: Thanks for noting that the data is out of date! However, this gem does *not* use any Avalara web APIs (it's entirely local). Instead it relies on a local, user-downloaded copy of [the estimated tax rates tables Avalara publishes](http://www.taxrates.com/download-tax-tables/).

To automate the downloading of those tables this gem does come with a list of the published tax rate table files. I've updated the gem to download the 2017 ones and parse them in 691ad60f7fc402c4cc0cc464a1bf25520ffd6452.
